# General Hugo Config
baseURL = "https://v-shenoy.com/"
theme = "archie"
title = "/home/v-shenoy"
copyright = "© Vighnesh Shenoy"
languageCode = "en-us"
enableEmoji = true
summaryLength = 50
enableGitInfo = true
cleanDestinationDir = true

[menu]
	[[menu.main]]
	identifier = "about"
	name = "about"
	url = "/about/"
	weight = 1

	[[menu.main]]
	identifier = "posts"
	name = "posts"
	url = "/posts/"
	weight = 2

	[[menu.main]]
	identifier = "tags"
	name = "tags"
	url = "/tags/"
	weight = 3

## Markup Configuration
[markup]
	[markup.highlight]
		style = "dracula"

# Archie Theme Config
[params]
	mode = "dark"
	useCDN = true
	subtitle = "Welcome to my personal corner of the internet!"
	favicon = "https://github.com/v-shenoy.png"
	customcss = ["css/custom.css"]

	[[params.social]]
	name = "RSS"
	icon = "rss"
	url = "/index.xml"

	[[params.social]]
	name = "E-mail"
	icon = "mail"
	url = "mailto:vighneshq@gmail.com"

	[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/v-shenoy"

	[[params.social]]
	name = "LinkedIn"
	icon = "linkedin"
	url = "https://www.linkedin.com/in/v-shenoy"

	[[params.social]]
	name = "Twitter"
	icon = "twitter"
	url = "https://twitter.com/bitsinadatabase"
